# Generated by Django 5.0 on 2023-12-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='pdf_file',
            new_name='file',
        ),
    ]
