# Generated by Django 5.0 on 2023-12-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_pdf_file_books_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
