# Generated by Django 5.0 on 2023-12-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book_image.jpg', upload_to='books/covers'),
        ),
    ]
