# Generated by Django 5.0 on 2023-12-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book_image.jpg', upload_to='simpledisplay/books/covers'),
        ),
    ]
